-- Phase 1: Database Updates

-- 1. Create the expenses table
CREATE TABLE IF NOT EXISTS expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date not null,
  invoice_number text, -- Bill/Invoice Number from Vendor
  vendor_name text not null,
  gstin text, -- specific vendor GSTIN
  taxable_amount numeric not null DEFAULT 0,
  gst_amount numeric not null DEFAULT 0, -- Input Tax Credit
  total_amount numeric not null DEFAULT 0,
  category text -- e.g., "Office Supplies", "Software", "Rent"
);

-- 2. Update invoices table to ensure GSTIN column exists (if not already)
-- Note: You might already have 'buyer_details' JSONB column, but a dedicated column is better for grouping.
-- If you use JSONB, we can extract it, but let's add a dedicated column for analytical ease.
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS buyer_gstin text;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS status text DEFAULT 'Generated'; -- For the status badge

-- 3. (Optional) Create a secure policy if Row Level Security is enabled
-- ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Enable read/write for all" ON expenses FOR ALL USING (true);
